# Generated by Django 5.1.5 on 2025-01-24 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogscommentmodel',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='app_blogs.blogsmodel', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='author',
            field=models.ManyToManyField(related_name='blogs', to='app_blogs.blogsauthormodel', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='app_blogs.blogscategorymodel', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
