# Generated by Django 5.1.5 on 2025-01-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0003_blogsauthormodel_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
