# Generated by Django 5.1.5 on 2025-01-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0004_blogsmodel_created_at_alter_blogsmodel_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='app_blogs.blogstagmodel', verbose_name='tags'),
        ),
    ]
