# Generated by Django 5.1.5 on 2025-01-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0005_blogsmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsauthormodel',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='blogsauthormodel',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='blogscategorymodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='blogscommentmodel',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='blogsmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='blogsmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='blogstagmodel',
            name='title_ru',
        ),
    ]
